#include "ui/gui/GuiMainWindowInteractionAdapterOps.h"

namespace arachno {

GuiMainModalMouseContext makeMainModalMouseContextFromWindowState(
    const GuiMainWindowInteractionAdapterContext& context,
    int playbackSampleRate) {
    return makeMainModalMouseContextFromWindowAdapterState(
        GuiMainModalMouseWindowAdapterInput {
            context.unsavedPrompt,
            context.unsavedPromptChoices,
            context.resolveUnsavedPrompt,
            context.instrumentBrowserActive,
            context.instrumentBrowserAcceptButton,
            context.instrumentBrowserCancelButton,
            context.instrumentBrowserListRect,
            context.instrumentBrowserHitTargets,
            context.instrumentBrowserSelected,
            context.instrumentBrowserScroll,
            context.closeInstrumentBrowser,
            context.audioTuningDialogActive,
            context.audioTuningDialogHits,
            context.audioTuningDialogRect,
            context.setAudioPerformanceMode,
            context.adjustAudioCustomLevel,
            context.resetAudioCustomLevel,
            context.inlinePrompt,
            context.synthWindowVisible,
            context.isSynthInlinePromptKind,
            context.inlinePromptUsesFileBrowser,
            context.inlinePromptButtonsVisible,
            context.inlinePromptAcceptButton,
            context.inlinePromptCancelButton,
            context.fileBrowserHits,
            context.fileBrowserListRect,
            context.fileBrowserScroll,
            context.fileBrowserSelected,
            context.fileBrowserEntries,
            context.fileBrowserDirectory,
            context.refreshFileBrowserEntries,
            context.executeInlinePrompt,
            context.cancelInlinePrompt},
        playbackSampleRate);
}

GuiMainWheelContext makeMainWheelContextFromWindowState(
    const GuiMainWindowInteractionAdapterContext& context,
    int button,
    int mx,
    int my,
    unsigned int stateMask) {
    return makeMainWheelContextFromWindowAdapterState(
        GuiMainWheelWindowAdapterInput {
            context.layout,
            context.sidebarViewport,
            context.instrumentListRect,
            context.sidebarContentHeight,
            context.sidebarScrollOffset,
            context.viewStartRow,
            context.draggingSelection,
            context.dragAnchorRow,
            context.dragAnchorTrack,
            context.gridTrackStart,
            context.activePatternRows,
            context.activeSnapshot,
            context.scrollInstrumentList,
            context.resizePatternRows,
            context.lockManualScroll,
            context.refreshSnapshot,
            context.gridPositionToCell,
            context.applySelectionRange},
        button,
        mx,
        my,
        stateMask);
}

GuiMainGridClickContext makeMainGridClickContextFromWindowState(
    const GuiMainWindowInteractionAdapterContext& context,
    int button,
    int mx,
    int my,
    bool altDown,
    bool shiftDown) {
    return makeMainGridClickContextFromWindowAdapterState(
        GuiMainGridClickWindowAdapterInput {
            context.paintNoteMidi,
            context.keyboardSelectionActive,
            context.paintingNotes,
            context.lastPaintRow,
            context.lastPaintTrack,
            context.draggingSelection,
            context.dragAnchorRow,
            context.dragAnchorTrack,
            context.gridPositionToCell,
            context.activeSnapshot,
            context.moveCursor,
            context.paintNoteAt,
            context.refreshSnapshot,
            context.runActionById,
            context.applySelectionRange},
        button,
        mx,
        my,
        altDown,
        shiftDown);
}

GuiMainMotionContext makeMainMotionContextFromWindowState(
    const GuiMainWindowInteractionAdapterContext& context,
    int mx,
    int my,
    unsigned int stateMask) {
    return makeMainMotionContextFromWindowAdapterState(
        GuiMainMotionWindowAdapterInput {
            context.pointerX,
            context.pointerY,
            context.windowWidth,
            context.windowHeight,
            context.layout,
            context.resizingSidebar,
            context.resizingTopPanel,
            context.draggingPatternRows,
            context.paintingNotes,
            context.draggingSelection,
            context.patternResizeAnchorY,
            context.patternResizeStartRows,
            context.topPanelHeightState,
            context.sidebarWidthState,
            context.paintNoteMidi,
            context.lastPaintRow,
            context.lastPaintTrack,
            context.dragAnchorRow,
            context.dragAnchorTrack,
            context.viewStartRow,
            context.hoveredTrackHeader,
            context.trackHeaderHits,
            context.resizePatternRows,
            context.gridPositionToCell,
            context.paintNoteAt,
            context.refreshSnapshot,
            context.applySelectionRange,
            context.lockManualScroll},
        mx,
        my,
        stateMask);
}

void syncInstrumentBrowserSelectionFromArmedFromWindowState(const GuiMainWindowInteractionAdapterContext& context) {
    syncInstrumentBrowserSelectionFromArmedInWindow(
        GuiMainInstrumentBrowserSyncInput {
            context.activeSnapshot,
            context.filteredInstrumentIndices,
            context.armedInstrument,
            context.instrumentBrowserSelected});
}

GuiMainKeyModalContext makeMainKeyModalContextFromWindowState(
    const GuiMainWindowInteractionAdapterContext& context,
    KeySym key,
    bool ctrlDown,
    bool shiftDown,
    bool altDown,
    int lookupCount,
    const char* lookupBuffer,
    const std::function<bool(KeySym)>& keyMatches,
    const std::function<int()>& resolvedDigit,
    int playbackSampleRate) {
    return makeMainKeyModalContextFromWindowAdapterState(
        GuiMainKeyModalWindowAdapterInput {
            context.unsavedPrompt.active,
            context.resolveUnsavedPrompt,
            context.audioTuningDialogActive,
            context.adjustAudioCustomLevel,
            context.setAudioPerformanceMode,
            context.inlinePrompt,
            context.synthWindowVisible,
            context.isSynthInlinePromptKind,
            context.inlinePromptUsesFileBrowser,
            context.fileBrowserSelected,
            context.fileBrowserScroll,
            context.fileBrowserListRect,
            context.fileBrowserEntries,
            context.fileBrowserDirectory,
            context.refreshFileBrowserEntries,
            context.executeInlinePrompt,
            context.cancelInlinePrompt,
            context.instrumentBrowserActive,
            context.instrumentBrowserSelected,
            context.instrumentBrowserScroll,
            context.instrumentBrowserQuery,
            context.closeInstrumentBrowser,
            context.cycleInstrumentBy,
            [&]() { syncInstrumentBrowserSelectionFromArmedFromWindowState(context); },
            [&]() {
                const AppSessionSnapshot snap = context.activeSnapshot();
                return static_cast<int>(context.filteredInstrumentIndices(snap).size());
            }},
        key,
        ctrlDown,
        shiftDown,
        altDown,
        lookupCount,
        lookupBuffer,
        keyMatches,
        resolvedDigit,
        playbackSampleRate);
}

GuiMainKeyEditContext makeMainKeyEditContextFromWindowState(
    const GuiMainWindowInteractionAdapterContext& context,
    KeySym key,
    bool ctrlDown,
    bool shiftDown,
    bool altDown,
    const std::function<bool(KeySym)>& keyMatches,
    const std::function<int()>& resolvedDigit) {
    return makeMainKeyEditContextFromWindowAdapterState(
        GuiMainKeyEditWindowAdapterInput {
            context.synthWindowVisible,
            context.stepAdvance,
            context.defaultVelocity,
            context.armedOctave,
            context.synthPreviewMidi,
            context.paintNoteMidi,
            context.activePatternRows,
            context.requestedRowCount,
            context.viewStartRow,
            context.keyboardSelectionActive,
            context.keyboardSelectionAnchorRow,
            context.keyboardSelectionAnchorTrack,
            context.setArmedOctave,
            context.applyArmedOctaveToSelection,
            context.ensureSynthKeyboardShowsMidi,
            context.cycleInstrumentBy,
            context.selectInstrument,
            context.auditionArmedInstrument,
            context.moveCursor,
            context.paintNoteAt,
            context.refreshSnapshot,
            context.ensurePatternRowsForRow,
            context.runActionById,
            context.applySelectionRange,
            context.lockManualScroll,
            context.activeSnapshot,
            context.runAction},
        key,
        ctrlDown,
        shiftDown,
        altDown,
        keyMatches,
        resolvedDigit);
}

GuiMainKeyCommandContext makeMainKeyCommandContextFromWindowState(
    const GuiMainWindowInteractionAdapterContext& context,
    KeySym key,
    bool ctrlDown,
    bool shiftDown,
    bool altDown,
    const std::function<bool(KeySym)>& keyMatches) {
    return makeMainKeyCommandContextFromWindowAdapterState(
        GuiMainKeyCommandWindowAdapterInput {
            context.audioTuningDialogActive,
            context.midiImportSplitByTrack,
            context.synthWindowVisible,
            context.targetSongLengthMinutes,
            context.themeMode,
            context.playbackSnapshot,
            context.selectedOrderIndex,
            context.setAudioPerformanceMode,
            context.currentPerformanceMode,
            context.runActionById,
            context.runSyncById,
            context.runEvents,
            context.openInstrumentBrowser,
            context.cycleInstrumentBy,
            context.runFileButtonAction,
            context.activeSnapshot,
            context.beginInlinePrompt,
            context.beginTemporalPastePrompt,
            context.beginPatternCreatePrompt,
            context.beginPatternClonePrompt,
            context.deleteActivePattern,
            context.setSynthWindowVisible,
            context.selectPatternIndex,
            context.selectOrderIndex,
            context.insertOrderAtSelection,
            context.appendOrderFromActivePattern,
            context.removeSelectedOrder,
            context.buildSongToTargetSeconds,
            context.trimSongToTargetSeconds,
            context.runAction},
        key,
        ctrlDown,
        shiftDown,
        altDown,
        keyMatches);
}

GuiMainKeyNoteContext makeMainKeyNoteContextFromWindowState(
    const GuiMainWindowInteractionAdapterContext& context,
    KeySym key,
    unsigned int keycode,
    bool ctrlDown,
    bool shiftDown,
    bool altDown,
    const std::function<bool(KeySym)>& keyMatches,
    const std::function<int()>& resolvedDigit) {
    return makeMainKeyNoteContextFromWindowAdapterState(
        GuiMainKeyNoteWindowAdapterInput {
            context.synthWindowVisible,
            context.armedOctave,
            context.armedInstrument,
            context.synthPreviewMidi,
            context.paintNoteMidi,
            context.stepAdvance,
            context.defaultVelocity,
            context.setArmedOctave,
            context.ensureSynthKeyboardShowsMidi,
            context.claimSynthPreviewKey,
            context.auditionSynthPreviewMidi,
            context.selectInstrument,
            context.activeSnapshot,
            context.ensurePatternRowsForRow,
            context.runActionWithRefresh},
        key,
        keycode,
        ctrlDown,
        shiftDown,
        altDown,
        keyMatches,
        resolvedDigit);
}

GuiMainButtonPressContextFactoryInput makeButtonPressFactoryInputFromWindowState(
    const GuiMainWindowInteractionAdapterContext& context) {
    return makeButtonPressFactoryInputFromWindowAdapterState(
        GuiMainButtonPressWindowAdapterInput {
            context.layout,
            context.gridTrackStart,
            context.selectedOrderIndex,
            context.transportButtons,
            context.fileButtons,
            context.themeButtons,
            context.audioPerformanceButtons,
            context.orderSlotHits,
            context.trackHeaderHits,
            context.gridTrackPrevButton,
            context.gridTrackNextButton,
            context.patternPrevButton,
            context.patternNextButton,
            context.patternNewButton,
            context.patternCloneButton,
            context.patternDeleteButton,
            context.orderPrevButton,
            context.orderNextButton,
            context.orderInsertButton,
            context.orderAppendButton,
            context.orderDeleteButton,
            context.octaveHitTargets,
            context.pianoKeyHits,
            context.trackMetadataHits,
            context.songLengthHits,
            context.midiImportSettingHits,
            context.instrumentControlHits,
            context.instrumentHitTargets,
            context.patternRowsMinus,
            context.patternRowsPlus,
            context.patternRowsValue,
            context.stepAdvanceButton,
            context.legatoButton,
            context.followPlaybackButton,
            context.draggingPatternRows,
            context.patternResizeAnchorY,
            context.patternResizeStartRows,
            context.activePatternRows,
            context.stepAdvance,
            context.followPlayback,
            context.paintNoteMidi,
            context.armedOctave,
            context.armedInstrument,
            context.targetSongLengthMinutes,
            context.midiImportRowsPerBeat,
            context.midiImportPatternRows,
            context.midiImportSplitByTrack,
            context.activeSnapshot,
            [&](const AppActionRequest& request) { (void)context.runAction(request); },
            context.runFileButtonAction,
            [&](GuiThemeMode mode) { context.themeMode = mode; },
            context.setAudioPerformanceMode,
            context.beginPatternCreatePrompt,
            context.beginPatternClonePrompt,
            context.deleteActivePattern,
            context.insertOrderAtSelection,
            context.appendOrderFromActivePattern,
            context.removeSelectedOrder,
            context.selectPatternIndex,
            context.selectOrderIndex,
            context.moveCursor,
            context.setArmedOctave,
            context.applyArmedOctaveToSelection,
            context.paintNoteAt,
            context.ensurePatternRowsForRow,
            context.refreshSnapshot,
            context.runTrackMetadataAction,
            context.resizePatternRows,
            context.beginInlinePrompt,
            context.buildSongToTargetSeconds,
            context.trimSongToTargetSeconds,
            context.selectInstrument,
            context.auditionArmedInstrument,
            context.openInstrumentBrowser});
}

} // namespace arachno
