#include "ui/gui/GuiMainWindowEventAdapterOps.h"

#include "AppActions.h"

namespace arachno {

GuiMainModalMouseContext makeMainModalMouseContextFromWindowAdapterState(
    const GuiMainModalMouseWindowAdapterInput& input,
    int playbackSampleRate) {
    return makeMainModalMouseContextFromState(
        GuiMainModalMouseContextFactoryInput {
            playbackSampleRate,
            input.unsavedPrompt,
            input.unsavedPromptChoices,
            input.resolveUnsavedPrompt,
            input.instrumentBrowserActive,
            input.instrumentBrowserAcceptButton,
            input.instrumentBrowserCancelButton,
            input.instrumentBrowserListRect,
            input.instrumentBrowserHitTargets,
            input.instrumentBrowserSelected,
            input.instrumentBrowserScroll,
            input.closeInstrumentBrowser,
            input.audioTuningDialogActive,
            input.audioTuningDialogHits,
            input.audioTuningDialogRect,
            input.setAudioPerformanceMode,
            input.adjustAudioCustomLevel,
            input.resetAudioCustomLevel,
            input.inlinePrompt,
            input.synthWindowVisible,
            input.isSynthInlinePromptKind,
            input.inlinePromptUsesFileBrowser,
            input.inlinePromptButtonsVisible,
            input.inlinePromptAcceptButton,
            input.inlinePromptCancelButton,
            input.fileBrowserHits,
            input.fileBrowserListRect,
            input.fileBrowserScroll,
            input.fileBrowserSelected,
            input.fileBrowserEntries,
            input.fileBrowserDirectory,
            input.refreshFileBrowserEntries,
            input.executeInlinePrompt,
            input.cancelInlinePrompt});
}

GuiMainWheelContext makeMainWheelContextFromWindowAdapterState(
    const GuiMainWheelWindowAdapterInput& input,
    int button,
    int mx,
    int my,
    unsigned int stateMask) {
    return makeMainWheelContextFromState(
        GuiMainWheelContextFactoryInput {
            button,
            mx,
            my,
            stateMask,
            input.layout,
            input.sidebarViewport,
            input.instrumentListRect,
            input.sidebarContentHeight,
            input.sidebarScrollOffset,
            input.viewStartRow,
            input.draggingSelection,
            input.dragAnchorRow,
            input.dragAnchorTrack,
            input.gridTrackStart,
            input.activePatternRows,
            input.activeSnapshot,
            input.scrollInstrumentList,
            input.resizePatternRows,
            input.lockManualScroll,
            input.refreshSnapshot,
            input.gridPositionToCell,
            input.applySelectionRange});
}

GuiMainGridClickContext makeMainGridClickContextFromWindowAdapterState(
    const GuiMainGridClickWindowAdapterInput& input,
    int button,
    int mx,
    int my,
    bool altDown,
    bool shiftDown) {
    return makeMainGridClickContextFromState(
        GuiMainGridClickContextFactoryInput {
            button,
            mx,
            my,
            altDown,
            shiftDown,
            input.paintNoteMidi,
            input.keyboardSelectionActive,
            input.paintingNotes,
            input.lastPaintRow,
            input.lastPaintTrack,
            input.draggingSelection,
            input.dragAnchorRow,
            input.dragAnchorTrack,
            input.gridPositionToCell,
            input.activeSnapshot,
            input.moveCursor,
            input.paintNoteAt,
            input.refreshSnapshot,
            input.runActionById,
            input.applySelectionRange});
}

GuiMainMotionContext makeMainMotionContextFromWindowAdapterState(
    const GuiMainMotionWindowAdapterInput& input,
    int mx,
    int my,
    unsigned int stateMask) {
    return makeMainMotionContextFromState(
        GuiMainMotionContextFactoryInput {
            mx,
            my,
            stateMask,
            input.pointerX,
            input.pointerY,
            input.windowWidth,
            input.windowHeight,
            input.layout,
            input.resizingSidebar,
            input.resizingTopPanel,
            input.draggingPatternRows,
            input.paintingNotes,
            input.draggingSelection,
            input.patternResizeAnchorY,
            input.patternResizeStartRows,
            input.topPanelHeightState,
            input.sidebarWidthState,
            input.paintNoteMidi,
            input.lastPaintRow,
            input.lastPaintTrack,
            input.dragAnchorRow,
            input.dragAnchorTrack,
            input.viewStartRow,
            input.hoveredTrackHeader,
            input.trackHeaderHits,
            input.resizePatternRows,
            input.gridPositionToCell,
            input.paintNoteAt,
            input.refreshSnapshot,
            input.applySelectionRange,
            input.lockManualScroll});
}

void syncInstrumentBrowserSelectionFromArmedInWindow(const GuiMainInstrumentBrowserSyncInput& input) {
    const AppSessionSnapshot snap = input.activeSnapshot();
    const std::vector<int> filtered = input.filteredInstrumentIndices(snap);
    for (int row = 0; row < static_cast<int>(filtered.size()); ++row) {
        if (filtered[static_cast<std::size_t>(row)] == input.armedInstrument) {
            input.instrumentBrowserSelected = row;
            break;
        }
    }
}

GuiMainKeyModalContext makeMainKeyModalContextFromWindowAdapterState(
    const GuiMainKeyModalWindowAdapterInput& input,
    KeySym key,
    bool ctrlDown,
    bool shiftDown,
    bool altDown,
    int lookupCount,
    const char* lookupBuffer,
    const std::function<bool(KeySym)>& keyMatches,
    const std::function<int()>& resolvedDigit,
    int playbackSampleRate) {
    return makeMainKeyModalContextFromState(
        GuiMainKeyModalContextFactoryInput {
            key,
            ctrlDown,
            shiftDown,
            altDown,
            lookupCount,
            lookupBuffer,
            keyMatches,
            resolvedDigit,
            input.unsavedPromptActive,
            input.resolveUnsavedPrompt,
            input.audioTuningDialogActive,
            playbackSampleRate,
            input.adjustAudioCustomLevel,
            input.setAudioPerformanceMode,
            input.inlinePrompt,
            input.synthWindowVisible,
            input.isSynthInlinePromptKind,
            input.inlinePromptUsesFileBrowser,
            input.fileBrowserSelected,
            input.fileBrowserScroll,
            input.fileBrowserListRect,
            input.fileBrowserEntries,
            input.fileBrowserDirectory,
            input.refreshFileBrowserEntries,
            input.executeInlinePrompt,
            input.cancelInlinePrompt,
            input.instrumentBrowserActive,
            input.instrumentBrowserSelected,
            input.instrumentBrowserScroll,
            input.instrumentBrowserQuery,
            input.closeInstrumentBrowser,
            input.cycleInstrumentBy,
            input.syncInstrumentBrowserSelectionFromArmed,
            input.filteredInstrumentCount});
}

GuiMainKeyEditContext makeMainKeyEditContextFromWindowAdapterState(
    const GuiMainKeyEditWindowAdapterInput& input,
    KeySym key,
    bool ctrlDown,
    bool shiftDown,
    bool altDown,
    const std::function<bool(KeySym)>& keyMatches,
    const std::function<int()>& resolvedDigit) {
    return makeMainKeyEditContextFromState(
        GuiMainKeyEditContextFactoryInput {
            key,
            ctrlDown,
            shiftDown,
            altDown,
            input.synthWindowVisible,
            input.stepAdvance,
            input.defaultVelocity,
            input.armedOctave,
            input.synthPreviewMidi,
            input.paintNoteMidi,
            input.activePatternRows,
            input.requestedRowCount,
            input.viewStartRow,
            input.keyboardSelectionActive,
            input.keyboardSelectionAnchorRow,
            input.keyboardSelectionAnchorTrack,
            keyMatches,
            resolvedDigit,
            input.setArmedOctave,
            input.applyArmedOctaveToSelection,
            input.ensureSynthKeyboardShowsMidi,
            input.cycleInstrumentBy,
            input.selectInstrument,
            input.auditionArmedInstrument,
            input.moveCursor,
            input.paintNoteAt,
            input.refreshSnapshot,
            input.ensurePatternRowsForRow,
            input.runActionById,
            input.applySelectionRange,
            input.lockManualScroll,
            input.activeSnapshot,
            input.runAction});
}

GuiMainKeyCommandContext makeMainKeyCommandContextFromWindowAdapterState(
    const GuiMainKeyCommandWindowAdapterInput& input,
    KeySym key,
    bool ctrlDown,
    bool shiftDown,
    bool altDown,
    const std::function<bool(KeySym)>& keyMatches) {
    const PlaybackSnapshot playback = input.playbackSnapshot();
    return makeMainKeyCommandContextFromState(
        GuiMainKeyCommandContextFactoryInput {
            key,
            ctrlDown,
            shiftDown,
            altDown,
            input.audioTuningDialogActive,
            input.midiImportSplitByTrack,
            input.synthWindowVisible,
            input.targetSongLengthMinutes,
            input.themeMode,
            playback.sampleRate,
            playback.state == TransportState::Playing,
            input.selectedOrderIndex,
            keyMatches,
            input.setAudioPerformanceMode,
            input.currentPerformanceMode,
            input.runActionById,
            input.runSyncById,
            input.runEvents,
            input.openInstrumentBrowser,
            input.cycleInstrumentBy,
            input.runFileButtonAction,
            input.activeSnapshot,
            input.beginInlinePrompt,
            input.beginTemporalPastePrompt,
            input.beginPatternCreatePrompt,
            input.beginPatternClonePrompt,
            input.deleteActivePattern,
            input.setSynthWindowVisible,
            input.selectPatternIndex,
            input.selectOrderIndex,
            input.insertOrderAtSelection,
            input.appendOrderFromActivePattern,
            input.removeSelectedOrder,
            input.buildSongToTargetSeconds,
            input.trimSongToTargetSeconds,
            input.runAction});
}

GuiMainKeyNoteContext makeMainKeyNoteContextFromWindowAdapterState(
    const GuiMainKeyNoteWindowAdapterInput& input,
    KeySym key,
    unsigned int keycode,
    bool ctrlDown,
    bool shiftDown,
    bool altDown,
    const std::function<bool(KeySym)>& keyMatches,
    const std::function<int()>& resolvedDigit) {
    return makeMainKeyNoteContextFromState(
        GuiMainKeyNoteContextFactoryInput {
            key,
            keycode,
            ctrlDown,
            shiftDown,
            altDown,
            input.synthWindowVisible,
            input.armedOctave,
            input.armedInstrument,
            input.synthPreviewMidi,
            input.paintNoteMidi,
            input.stepAdvance,
            input.defaultVelocity,
            keyMatches,
            resolvedDigit,
            input.setArmedOctave,
            input.ensureSynthKeyboardShowsMidi,
            input.claimSynthPreviewKey,
            input.auditionSynthPreviewMidi,
            input.selectInstrument,
            input.activeSnapshot,
            input.ensurePatternRowsForRow,
            input.runActionWithRefresh});
}

GuiMainButtonPressContextFactoryInput makeButtonPressFactoryInputFromWindowAdapterState(
    const GuiMainButtonPressWindowAdapterInput& input) {
    return GuiMainButtonPressContextFactoryInput {
        input.layout,
        input.gridTrackStart,
        input.selectedOrderIndex,
        input.transportButtons,
        input.fileButtons,
        input.themeButtons,
        input.audioPerformanceButtons,
        input.orderSlotHits,
        input.trackHeaderHits,
        input.gridTrackPrevButton,
        input.gridTrackNextButton,
        input.patternPrevButton,
        input.patternNextButton,
        input.patternNewButton,
        input.patternCloneButton,
        input.patternDeleteButton,
        input.orderPrevButton,
        input.orderNextButton,
        input.orderInsertButton,
        input.orderAppendButton,
        input.orderDeleteButton,
        input.octaveHitTargets,
        input.pianoKeyHits,
        input.trackMetadataHits,
        input.songLengthHits,
        input.midiImportSettingHits,
        input.instrumentControlHits,
        input.instrumentHitTargets,
        input.patternRowsMinus,
        input.patternRowsPlus,
        input.patternRowsValue,
        input.stepAdvanceButton,
        input.followPlaybackButton,
        input.draggingPatternRows,
        input.patternResizeAnchorY,
        input.patternResizeStartRows,
        input.activePatternRows,
        input.stepAdvance,
        input.followPlayback,
        input.paintNoteMidi,
        input.armedOctave,
        input.armedInstrument,
        input.targetSongLengthMinutes,
        input.midiImportRowsPerBeat,
        input.midiImportPatternRows,
        input.midiImportSplitByTrack,
        input.activeSnapshot,
        input.runActionRequest,
        input.runFileButtonAction,
        input.setThemeMode,
        input.setAudioPerformanceMode,
        input.beginPatternCreatePrompt,
        input.beginPatternClonePrompt,
        input.deleteActivePattern,
        input.insertOrderAtSelection,
        input.appendOrderFromActivePattern,
        input.removeSelectedOrder,
        input.selectPatternIndex,
        input.selectOrderIndex,
        input.moveCursor,
        input.setArmedOctave,
        input.applyArmedOctaveToSelection,
        input.paintNoteAt,
        input.ensurePatternRowsForRow,
        input.refreshSnapshot,
        input.runTrackMetadataAction,
        input.resizePatternRows,
        input.beginInlinePrompt,
        input.buildSongToTargetSeconds,
        input.trimSongToTargetSeconds,
        input.selectInstrument,
        input.auditionArmedInstrument,
        input.openInstrumentBrowser};
}

} // namespace arachno
