#include "ui/gui/GuiSynthEventContextFactoryOps.h"

namespace arachno {

GuiSynthKeyContext makeSynthKeyContextFromState(const GuiSynthKeyContextFactoryInput& input) {
    return GuiSynthKeyContext {
        input.inlinePrompt,
        input.isSynthInlinePromptKind,
        input.inlinePromptUsesFileBrowser,
        input.synthInlinePromptButtonsVisible,
        input.synthInlinePromptAcceptButton,
        input.synthInlinePromptCancelButton,
        input.fileBrowserHits,
        input.fileBrowserListRect,
        input.fileBrowserScroll,
        input.fileBrowserSelected,
        input.fileBrowserEntries,
        input.fileBrowserDirectory,
        input.refreshFileBrowserEntries,
        input.executeInlinePrompt,
        input.cancelInlinePrompt,
        input.armedOctave,
        input.synthPreviewMidi,
        input.paintNoteMidi,
        input.setArmedOctave,
        input.ensureSynthKeyboardShowsMidi,
        input.setSynthWindowVisible,
        input.cycleInstrument,
        input.auditionSynthPreviewMidi,
        input.claimSynthPreviewKey,
        input.releaseSynthPreviewKey};
}

GuiSynthClickContext makeSynthClickContextFromState(const GuiSynthClickContextFactoryInput& input) {
    return GuiSynthClickContext {
        input.session,
        input.mx,
        input.my,
        input.synthLastPointerMidi,
        input.synthKeyboardBaseOctave,
        input.synthKeyboardVisibleOctaves,
        input.armedOctave,
        input.synthParamPage,
        input.synthParamScroll,
        input.synthParamOscTarget,
        input.synthParamDragStartX,
        input.synthParamDragStartY,
        input.synthParamDragStartValue,
        input.synthParamDragLastValue,
        input.synthParamDragActive,
        input.synthParamDragKnob,
        input.synthParamDragDirty,
        input.synthParamDragName,
        input.synthParamDragRect,
        input.synthPreviewMidi,
        input.synthWindowHits,
        input.clampInstrumentIndex,
        input.setSynthWindowVisible,
        input.selectInstrument,
        input.auditionArmedInstrument,
        input.auditionSynthPreviewMidi,
        input.auditionSynthOscillatorPreview,
        input.runAction,
        input.beginInlinePrompt,
        input.activeSnapshot,
        input.setSynthWaveform,
        input.setSynthParameter,
        input.findSynthParamDef,
        input.getSynthParameterValue};
}

GuiSynthWindowEventContext makeSynthWindowEventContextFromState(
    const GuiSynthWindowEventContextFactoryInput& input) {
    return GuiSynthWindowEventContext {
        input.display,
        input.synthWindow,
        input.wmDelete,
        input.synthWindowWidth,
        input.synthWindowHeight,
        input.synthWindowMinWidth,
        input.synthWindowMinHeight,
        input.ensureSynthBackbuffer,
        input.setSynthWindowVisible,
        input.synthPointerX,
        input.synthPointerY,
        input.synthPointerDown,
        input.synthLastPointerMidi,
        input.synthParamDragActive,
        input.synthParamDragKnob,
        input.synthParamDragDirty,
        input.synthParamDragName,
        input.synthParamDragRect,
        input.synthParamDragStartX,
        input.synthParamDragStartY,
        input.synthParamDragStartValue,
        input.synthParamDragLastValue,
        input.synthTooltipParam,
        input.synthTooltipHoverSince,
        input.synthParamViewport,
        input.synthParamContentHeight,
        input.synthParamScroll,
        input.synthWindowHits,
        input.inlinePrompt,
        input.isSynthInlinePromptKind,
        input.inlinePromptUsesFileBrowser,
        input.synthInlinePromptButtonsVisible,
        input.synthInlinePromptAcceptButton,
        input.synthInlinePromptCancelButton,
        input.fileBrowserHits,
        input.fileBrowserListRect,
        input.fileBrowserScroll,
        input.fileBrowserSelected,
        input.fileBrowserEntries,
        input.fileBrowserDirectory,
        input.refreshFileBrowserEntries,
        input.executeInlinePrompt,
        input.cancelInlinePrompt,
        input.triggerSynthKeyboardPointer,
        input.handleSynthWindowClick,
        input.refreshSnapshot,
        input.clampInstrumentIndex,
        input.findSynthParamDef,
        input.setSynthParameter,
        input.makeSynthKeyContext,
        input.isAutoRepeatRelease};
}

} // namespace arachno
