#include "ui/gui/GuiWindowMainInteractionFactoryOps.h"

namespace arachno {

GuiMainWindowInteractionAdapterContext makeMainInteractionContextFromWindowState(
    const GuiWindowMainInteractionFactoryInput& input) {
    auto audibleTrackCount = input.audibleTrackCount;
    auto moveCursor = input.editingBindings.moveCursor;
    auto deleteActivePattern = input.editingBindings.deleteActivePattern;
    auto insertOrderAtSelection = input.editingBindings.insertOrderAtSelection;
    auto appendOrderFromActivePattern = input.editingBindings.appendOrderFromActivePattern;
    auto removeSelectedOrder = input.editingBindings.removeSelectedOrder;
    auto* audioRuntime = &input.audioRuntime;

    return GuiMainWindowInteractionAdapterContext {
        input.unsavedPrompt,
        input.unsavedPromptChoices,
        input.resolveUnsavedPrompt,
        input.instrumentBrowserActive,
        input.instrumentBrowserAcceptButton,
        input.instrumentBrowserCancelButton,
        input.instrumentBrowserListRect,
        input.instrumentBrowserHitTargets,
        input.instrumentBrowserSelected,
        input.instrumentBrowserScroll,
        input.instrumentBrowserQuery,
        input.instrumentBindings.closeInstrumentBrowser,
        input.audioTuningDialogActive,
        input.audioTuningDialogHits,
        input.audioTuningDialogRect,
        input.setAudioPerformanceMode,
        input.adjustAudioCustomLevel,
        [audioRuntime, audibleTrackCount](int sampleRate) {
            audioRuntime->setCustomLevel(0, sampleRate, audibleTrackCount());
        },
        input.inlinePrompt,
        input.synthWindowVisible,
        input.isSynthInlinePromptKind,
        input.inlinePromptUsesFileBrowser,
        input.inlinePromptButtonsVisible,
        input.inlinePromptAcceptButton,
        input.inlinePromptCancelButton,
        input.fileBrowserHits,
        input.fileBrowserListRect,
        input.fileBrowserScroll,
        input.fileBrowserSelected,
        input.fileBrowserEntries,
        input.fileBrowserDirectory,
        input.refreshFileBrowserEntries,
        input.executeInlinePrompt,
        input.cancelInlinePrompt,
        input.layout,
        input.sidebarViewport,
        input.instrumentListRect,
        input.sidebarContentHeight,
        input.sidebarScrollOffset,
        input.viewStartRow,
        input.draggingSelection,
        input.dragAnchorRow,
        input.dragAnchorTrack,
        input.gridTrackStart,
        input.activePatternRows,
        input.paintNoteMidi,
        input.keyboardSelectionActive,
        input.keyboardSelectionAnchorRow,
        input.keyboardSelectionAnchorTrack,
        input.paintingNotes,
        input.lastPaintRow,
        input.lastPaintTrack,
        input.pointerX,
        input.pointerY,
        input.windowWidth,
        input.windowHeight,
        input.resizingSidebar,
        input.resizingTopPanel,
        input.draggingPatternRows,
        input.patternResizeAnchorY,
        input.patternResizeStartRows,
        input.topPanelHeightState,
        input.sidebarWidthState,
        input.hoveredTrackHeader,
        input.trackHeaderHits,
        input.armedInstrument,
        input.armedOctave,
        input.stepAdvance,
        input.defaultVelocity,
        input.synthPreviewMidi,
        input.requestedRowCount,
        input.midiImportSplitByTrack,
        input.targetSongLengthMinutes,
        input.themeMode,
        input.selectedOrderIndex,
        input.midiImportRowsPerBeat,
        input.midiImportPatternRows,
        input.followPlayback,
        input.transportButtons,
        input.fileButtons,
        input.themeButtons,
        input.audioPerformanceButtons,
        input.orderSlotHits,
        input.gridTrackPrevButton,
        input.gridTrackNextButton,
        input.patternPrevButton,
        input.patternNextButton,
        input.patternNewButton,
        input.patternCloneButton,
        input.patternDeleteButton,
        input.orderPrevButton,
        input.orderNextButton,
        input.orderInsertButton,
        input.orderAppendButton,
        input.orderDeleteButton,
        input.octaveHitTargets,
        input.pianoKeyHits,
        input.trackMetadataHits,
        input.songLengthHits,
        input.midiImportSettingHits,
        input.instrumentControlHits,
        input.instrumentHitTargets,
        input.patternRowsMinus,
        input.patternRowsPlus,
        input.patternRowsValue,
        input.stepAdvanceButton,
        input.legatoButton,
        input.followPlaybackButton,
        input.activeSnapshot,
        input.instrumentBindings.scrollInstrumentList,
        input.resizePatternRows,
        input.lockManualScroll,
        input.refreshSnapshot,
        input.editingBindings.gridPositionToCell,
        input.editingBindings.applySelectionRange,
        [moveCursor](int row, int track) { (void)moveCursor(row, track, true); },
        input.editingBindings.paintNoteAt,
        input.runActionById,
        input.runAction,
        input.runActionWithRefresh,
        input.runSyncById,
        input.runEvents,
        input.playbackSnapshot,
        input.currentPerformanceMode,
        input.setArmedOctave,
        input.applyArmedOctaveToSelection,
        input.ensurePatternRowsForRow,
        input.instrumentBindings.auditionArmedInstrument,
        input.instrumentBindings.cycleInstrumentBy,
        input.instrumentBindings.selectInstrument,
        input.instrumentBindings.auditionSynthPreviewMidi,
        input.claimSynthPreviewKey,
        input.editingBindings.beginTemporalPastePrompt,
        input.editingBindings.beginPatternCreatePrompt,
        input.editingBindings.beginPatternClonePrompt,
        [deleteActivePattern]() { (void)deleteActivePattern(); },
        input.setSynthWindowVisible,
        input.editingBindings.selectPatternIndex,
        input.editingBindings.selectOrderIndex,
        [insertOrderAtSelection]() { (void)insertOrderAtSelection(); },
        [appendOrderFromActivePattern]() { (void)appendOrderFromActivePattern(); },
        [removeSelectedOrder]() { (void)removeSelectedOrder(); },
        input.editingBindings.buildSongToTargetSeconds,
        input.editingBindings.trimSongToTargetSeconds,
        input.runFileButtonAction,
        input.instrumentBindings.openInstrumentBrowser,
        input.beginInlinePrompt,
        input.instrumentBindings.filteredInstrumentIndices,
        input.ensureSynthKeyboardShowsMidi,
        input.editingBindings.runTrackMetadataAction};
}

} // namespace arachno
