#include "ui/gui/GuiWindowSynthInteractionFactoryOps.h"

namespace arachno {

GuiSynthWindowInteractionAdapterContext makeSynthInteractionContextFromWindowState(
    const GuiWindowSynthInteractionFactoryInput& input) {
    return GuiSynthWindowInteractionAdapterContext {
        input.session,
        input.display,
        input.synthWindow,
        input.wmDelete,
        input.synthWindowWidth,
        input.synthWindowHeight,
        input.synthWindowMinWidth,
        input.synthWindowMinHeight,
        input.ensureSynthBackbuffer,
        input.setSynthWindowVisible,
        input.synthWindowVisible,
        input.synthWindowNeedsRedraw,
        input.needsRedraw,
        input.synthPointerX,
        input.synthPointerY,
        input.synthPointerDown,
        input.synthLastPointerMidi,
        input.synthParamDragActive,
        input.synthParamDragKnob,
        input.synthParamDragDirty,
        input.synthParamDragName,
        input.synthParamDragRect,
        input.synthParamDragStartX,
        input.synthParamDragStartY,
        input.synthParamDragStartValue,
        input.synthParamDragLastValue,
        input.synthTooltipParam,
        input.synthTooltipHoverSince,
        input.synthParamViewport,
        input.synthParamContentHeight,
        input.synthParamScroll,
        input.synthKeyboardBaseOctave,
        input.synthKeyboardVisibleOctaves,
        input.synthParamPage,
        input.synthParamOscTarget,
        input.armedOctave,
        input.armedInstrument,
        input.synthPreviewMidi,
        input.paintNoteMidi,
        input.stepAdvance,
        input.defaultVelocity,
        input.synthWindowHits,
        input.synthKeyboardHits,
        input.inlinePrompt,
        input.isSynthInlinePromptKind,
        input.inlinePromptUsesFileBrowser,
        input.synthInlinePromptButtonsVisible,
        input.synthInlinePromptAcceptButton,
        input.synthInlinePromptCancelButton,
        input.fileBrowserHits,
        input.fileBrowserListRect,
        input.fileBrowserScroll,
        input.fileBrowserSelected,
        input.fileBrowserEntries,
        input.fileBrowserDirectory,
        input.refreshFileBrowserEntries,
        input.executeInlinePrompt,
        input.cancelInlinePrompt,
        input.ensureSynthKeyboardShowsMidi,
        input.cycleInstrumentBy,
        input.setArmedOctave,
        input.claimSynthPreviewKey,
        input.releaseSynthPreviewKey,
        input.auditionSynthPreviewMidi,
        input.auditionSynthPreviewMidiVelocity,
        input.auditionSynthOscillatorPreview,
        input.auditionArmedInstrument,
        input.selectInstrument,
        input.clampInstrumentIndex,
        input.activeSnapshot,
        input.runAction,
        input.setSynthWaveform,
        input.setSynthParameter,
        input.setSynthParameterWithRefresh,
        input.findSynthParamDef,
        input.getSynthParameterValue,
        input.beginInlinePrompt,
        input.refreshSnapshot,
        input.midiInput,
        input.synthMidiPreviewHeld};
}

} // namespace arachno
